### ISSUE TITLE
Unable to have multiple events

### ISSUE THREAD

**Issue by TheUntraceable** [SawshaDev/wharf#6]
Hey, I saw this repo in TCR and it was interesting, it took a nice approach to wrapping the Discord API and gateway. I was skimming through the code out of curiosity (and so I could see what I could help with), and I found [this line](https://github.com/SawshaDev/wharf/blob/main/wharf/dispatcher.py#L67). From what I can see without any testing is that this function is called in the `subscribe` function, and it *blindly resets the events to a list*. If I've understood that correctly, what you *should* do is use a [defaultdict](https://docs.python.org/3/library/collections.html#collections.defaultdict), with `list` as the argument. This means you don't need to do none of the `if not self.events.get(event_name)`, and can go straight to the `self.events[event_name].append`. I hope this helps you. Keep up the solid work 👍

**Comment by SawshaDev** [comment]
Ahh thanks for catching that, ill fix in a tiny bit, till than ill keep the issue open until i get it fixed, thanks for catching that though 👍🏻

**Comment by SawshaDev** [comment]
fixed in 414ef57
