### ISSUE TITLE
Incorrect handling of reconnect opcode.

### ISSUE THREAD

**Issue by TheUntraceable** [SawshaDev/wharf#8]
I saw [this](https://github.com/SawshaDev/wharf/blob/main/wharf/gateway.py#L213) and matched it against [the docs](https://discord.com/developers/docs/topics/opcodes-and-status-codes#opcodes-and-status-codes), and when you receive it, you should attempt to reconnect and resume immediately.

**Comment by SawshaDev** [comment]
You're not supposed to send the resume payload inn the reconnect Opcode, only in the hello opcode, so this issue is invalid

**Comment by SawshaDev** [comment]
Fixed in #9
